#!/usr/bin/env python3
"""Generate C header with embedded JS sources as string literals.

Usage: python3 scripts/gen_js_embed.py

Reads JS sources from ../embedded-prolog/src/ and dens/lib/,
strips ESM import/export lines, writes readable C string literals into
vendor/prolog/prolog_js_embed.h and vendor/prolog/den_engine_js_embed.h.
"""

import os

STRATA_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EP_SRC = os.path.join(STRATA_ROOT, "..", "embedded-prolog", "src")
DENS_LIB = os.path.join(STRATA_ROOT, "dens", "lib")
VENDOR = os.path.join(STRATA_ROOT, "vendor", "prolog")


def strip_esm(source):
    """Remove ESM import/export lines from JS source."""
    lines = source.split("\n")
    out = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("import "):
            continue
        if stripped.startswith("export "):
            continue
        out.append(line)
    while out and out[-1].strip() == "":
        out.pop()
    return "\n".join(out) + "\n"


def to_c_string(source, var_name):
    """Convert string to a C string literal — readable and auditable."""
    lines = source.split("\n")
    out = []
    out.append(f"static const char {var_name}[] =")
    for i, line in enumerate(lines):
        escaped = line.replace("\\", "\\\\").replace('"', '\\"')
        out.append(f'  "{escaped}\\n"')
    out.append(";\n")
    return "\n".join(out)


def read_file(path):
    with open(path, "r") as f:
        return f.read()


def make_loadstring_js():
    """Minimal loadString that works in QuickJS global scope."""
    return """\
// loadString — load Prolog text into a PrologEngine
// Depends on parseProgram (from parser.js) being a global.

function loadString(engine, text) {
  var clauses = parseProgram(text);
  for (var i = 0; i < clauses.length; i++) {
    engine.addClause(clauses[i].head, clauses[i].body);
  }
  return clauses.length;
}
"""


def gen_prolog_js_embed():
    sources = [
        (os.path.join(EP_SRC, "reactive.js"), "js_reactive_src"),
        (os.path.join(EP_SRC, "prolog-engine.js"), "js_prolog_engine_src"),
        (os.path.join(EP_SRC, "parser.js"), "js_parser_src"),
        (os.path.join(EP_SRC, "reactive-prolog.js"), "js_reactive_prolog_src"),
    ]

    header = '/* Auto-generated by scripts/gen_js_embed.py — do not edit.\n'
    header += '   Source: embedded-prolog/src/ */\n'
    header += '#ifndef PROLOG_JS_EMBED_H\n#define PROLOG_JS_EMBED_H\n\n'

    for path, var_name in sources:
        raw = read_file(path)
        clean = strip_esm(raw)
        header += to_c_string(clean, var_name) + "\n"

    ls_src = make_loadstring_js()
    header += to_c_string(ls_src, "js_load_string_src") + "\n"

    header += "#endif\n"

    out_path = os.path.join(VENDOR, "prolog_js_embed.h")
    with open(out_path, "w") as f:
        f.write(header)
    print(f"wrote {out_path} ({len(header)} bytes)")


def gen_den_engine_js_embed():
    sources = [
        (os.path.join(DENS_LIB, "den-engine.js"), "js_den_engine_src"),
        (os.path.join(DENS_LIB, "den-runtime.js"), "js_den_runtime_src"),
    ]

    header = '/* Auto-generated by scripts/gen_js_embed.py — do not edit.\n'
    header += '   Source: dens/lib/ */\n'
    header += '#ifndef DEN_ENGINE_JS_EMBED_H\n#define DEN_ENGINE_JS_EMBED_H\n\n'

    for path, var_name in sources:
        raw = read_file(path)
        clean = strip_esm(raw)
        header += to_c_string(clean, var_name) + "\n"

    header += "#endif\n"

    out_path = os.path.join(VENDOR, "den_engine_js_embed.h")
    with open(out_path, "w") as f:
        f.write(header)
    print(f"wrote {out_path} ({len(header)} bytes)")


if __name__ == "__main__":
    gen_prolog_js_embed()
    gen_den_engine_js_embed()
    print("done")
